run:
  deadline: 30m
  issues-exit-code: 1
  tests: false
  skip-dirs:
    - vendor$
    - third_party$
    - testdata$
    - examples$
    - protobuf$
    - schema$
  modules-download-mode: vendor

output:
  format: tab
  print-issued-lines: true
  print-linter-name: true

linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - unparam
    - gochecknoglobals
    - goerr113
    - godot
    - gosec

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G202"
    - linters:
        - lll
      source: "^//go:generate "
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "Error return value of `logger.InfoLogger.Log` is not checked"
      linters:
        - errcheck
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - scopelint
        - funlen
    - linters:
        - gomnd
      source: "os.exit"
    - linters:
        - interfacer
      text: "can be `fmt.Stringer`"
    - linters:
        - staticcheck
      source: "defer rows.Close()"
    - linters:
        - gosec
      source: "POSTGRES_PASSWORD"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocyclo:
    min-complexity: 30
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 2
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/davecgh/go-spew/spew
  misspell:
    locale: US
  lll:
    line-length: 120
    tab-width: 1
  funlen:
    lines: 85
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 64
