language: go

go: 1.15

services: docker

jobs:
  include:
    - stage: lint
      name: "Linter"
      install:
        - docker pull golangci/golangci-lint:v1.32.2
      script:
        - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.32.2 golangci-lint run
    - stage: test
      name: "Unit Tests"
      script:
        - go test ./...